# Generated by Django 3.1.6 on 2021-09-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genes', '0001_initial'),
        ('organisms', '0002_auto_20210328_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('docfile', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geneset',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('size', models.IntegerField(default=0)),
                ('grouping', models.CharField(max_length=64)),
                ('function_database', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parentset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.gene')),
                ('geneset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1.geneset')),
            ],
        ),
        migrations.CreateModel(
            name='OrganismGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1.geneset')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisms.organism')),
            ],
        ),
        migrations.AddField(
            model_name='geneset',
            name='genes',
            field=models.ManyToManyField(through='a1.Parentset', to='genes.Gene'),
        ),
        migrations.AddField(
            model_name='geneset',
            name='organism',
            field=models.ManyToManyField(through='a1.OrganismGS', to='organisms.Organism'),
        ),
    ]
