# Generated by Django 3.1.6 on 2021-10-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0003_gene_geneset_name'),
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parentset',
            new_name='Geneset_membership',
        ),
    ]
