# Generated by Django 3.1.6 on 2021-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisms', '0002_auto_20210328_1410'),
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geneset',
            name='organisms',
        ),
        migrations.AddField(
            model_name='geneset',
            name='orgs',
            field=models.ManyToManyField(to='organisms.Organism'),
        ),
    ]
