# Generated by Django 3.1.6 on 2021-04-22 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisms', '0002_auto_20210328_1410'),
        ('a1', '0002_auto_20210422_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geneset',
            name='orgs',
        ),
        migrations.AddField(
            model_name='geneset',
            name='organism',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisms.organism'),
            preserve_default=False,
        ),
    ]
