# Generated by Django 3.1.6 on 2021-10-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0002_auto_20211004_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geneset',
            old_name='function_database',
            new_name='setname',
        ),
    ]
