# Generated by Django 3.1.6 on 2021-04-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisms', '0002_auto_20210328_1410'),
        ('genes', '0001_initial'),
        ('a1', '0003_auto_20210422_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.gene')),
                ('geneset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1.geneset')),
            ],
        ),
        migrations.CreateModel(
            name='OrganismGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1.geneset')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisms.organism')),
            ],
        ),
    ]
