# Generated by Django 3.1.6 on 2021-04-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisms', '0002_auto_20210328_1410'),
        ('genes', '0001_initial'),
        ('a1', '0004_organismgs_parentset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organismgs',
            old_name='org',
            new_name='organism',
        ),
        migrations.RemoveField(
            model_name='geneset',
            name='genes',
            field=models.ManyToManyField(through='a1.Parentset', to='genes.Gene'),
        ),
        migrations.RemoveField(
            model_name='geneset',
            name='organism',
        ),
        migrations.AddField(
            model_name='geneset',
            name='organism',
            field=models.ManyToManyField(through='a1.OrganismGS', to='organisms.Organism'),
        ),
    ]
